"""
generate_short.py — YouTube Shorts generator for Midnight Cabin

Strategy:
- Rotates 3 hook styles: POV emotional / Educational / Contrast reveal
- Theme-specific start offsets for best-sounding moment
- Audio reveal: fades from 20% to 100% in first 3s for satisfying impact
- Vertical 1080x1920, 30fps, #Shorts format
"""

import json
import os
import platform
import random
import subprocess
from datetime import datetime

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PERSISTENT_DIR = os.environ.get("PERSISTENT_DIR", "/data")

IDEA_PATH = os.path.join(PERSISTENT_DIR, "current_idea.json")
if not os.path.exists(IDEA_PATH):
    IDEA_PATH = os.path.join(BASE_DIR, "current_idea.json")

SOURCE_VIDEO = os.path.join(BASE_DIR, "output", "video.mp4")
SHORT_OUTPUT = os.path.join(BASE_DIR, "output", "short.mp4")
VOICEOVER_PATH = os.path.join(BASE_DIR, "output", "voiceover.mp3")
SHORT_ROTATION_FILE = os.path.join(PERSISTENT_DIR, "short_hook_rotation.json")

SHORT_DURATION = 60

# ─────────────────────────────────────────────
# LOAD IDEA
# ─────────────────────────────────────────────
with open(IDEA_PATH) as f:
    idea = json.load(f)

theme = idea.get("theme", "Ambient Soundscape")
layers = idea.get("sound_layers", ["brown_noise"])
primary = idea.get("audio_strategy", {}).get("primary_category", "brown_noise")
mood = idea.get("audio_strategy", {}).get("mood", "calm")
duration_minutes = idea.get("duration_minutes", 480)
duration_label = "10 Hours" if duration_minutes >= 600 else "8 Hours"

def strip_emojis(text):
    """Remove emojis — ffmpeg drawtext doesn't support them without emoji font."""
    import re
    emoji_pattern = re.compile(
        "["
        "😀-🙏"
        "🌀-🗿"
        "🚀-🛿"
        "🇠-🇿"
        "✀-➿"
        "🤀-🧿"
        "☀-⛿"
        "🨀-🩯"
        "🩰-🫿"
        "]+",
        flags=re.UNICODE
    )
    return emoji_pattern.sub("", text).strip()

is_flagship = idea.get("is_flagship") or idea.get("content_tier") == "flagship"
flagship_shorts = (idea.get("flagship_package", {}) or {}).get("shorts", [])
print(f"Generating Short for: {theme} ({primary}) | flagship={is_flagship}")

# ─────────────────────────────────────────────
# HOOK ROTATION — cycles POV → Educational → Contrast
# ─────────────────────────────────────────────
HOOK_STYLES = ["pov", "educational"]

if os.path.exists(SHORT_ROTATION_FILE):
    with open(SHORT_ROTATION_FILE) as f:
        rotation = json.load(f)
    last_style = rotation.get("last_style", "contrast")
    idx = HOOK_STYLES.index(last_style) if last_style in HOOK_STYLES else -1
    hook_style = HOOK_STYLES[(idx + 1) % len(HOOK_STYLES)]
else:
    hook_style = "pov"

with open(SHORT_ROTATION_FILE, "w") as f:
    json.dump({"last_style": hook_style}, f)

print(f"Hook style this Short: {hook_style}")

# ─────────────────────────────────────────────
# HOOK TEXT + VOICEOVER — generated by Claude
# ─────────────────────────────────────────────

SOFT_CTAS = [
    "Full version on Midnight Cabin.",
    "Save this for tonight.",
    "Let the full version play later.",
]

# Fallback hooks if LLM fails
POV_HOOKS_FALLBACK = {
    "rain":         "POV: The rain finally arrived",
    "fireplace":    "POV: Nowhere else to be tonight",
    "river":        "POV: You hear water outside",
    "ocean_waves":  "POV: The ocean keeps breathing",
    "soft_wind":    "POV: Midnight wind through trees",
    "night_forest": "POV: The forest is completely still",
    "brown_noise":  "POV: Your thoughts get quieter",
}

EDUCATIONAL_HOOKS_FALLBACK = {
    "rain":         "Rain masks every other sound",
    "fireplace":    "Fire fills silence without music",
    "river":        "Flowing water quiets a busy mind",
    "ocean_waves":  "Waves arrive at their own pace",
    "soft_wind":    "Wind without sudden sharp edges",
    "night_forest": "Nature sound with no surprises",
    "brown_noise":  "Brown noise lowers the contrast",
}

FALLBACK_HOOKS = {
    "pov": POV_HOOKS_FALLBACK,
    "educational": EDUCATIONAL_HOOKS_FALLBACK,
}

POV_VOICEOVERS_FALLBACK = {
    "rain": f"Steady rain gives your mind one thing to follow. Nothing sharp, nothing sudden, just sound moving at its own pace. Save this for tonight.",
    "fireplace": f"A crackling fire fills the room without asking for attention. Just warmth and a quiet kind of company. Let the full version play later.",
    "river": f"A river never rushes you. It keeps moving and gives your mind a soft pattern to rest against. Full version on Midnight Cabin.",
    "ocean_waves": f"The ocean arrives, fades, and returns. No hurry, no sharp edges. Let one wave replace one thought. Save this for tonight.",
    "soft_wind": f"Soft wind is the sound of nothing needing you right now. Just a quiet room and steady air outside. Full version on Midnight Cabin.",
    "night_forest": f"The forest is not silent but nothing is demanding your attention. That is what makes it feel restful. Save this for tonight.",
    "brown_noise": f"Brown noise raises the noise floor so sudden sounds blend in. Your brain stops scanning and starts settling. Full version on Midnight Cabin.",
}

EDUCATIONAL_VOICEOVERS_FALLBACK = {
    "rain": f"Your auditory system keeps scanning for threats even while you sleep. Steady rain raises the noise floor so sudden sounds blend in. Full version on Midnight Cabin.",
    "fireplace": f"Irregular crackling keeps your auditory cortex just engaged enough to quiet intrusive thoughts. Not enough to keep you awake. Save this for tonight.",
    "river": f"Pink noise in flowing water matches the brain's own resting rhythms. Your mind recognises it and slows down. Full version on Midnight Cabin.",
    "ocean_waves": f"Ocean waves oscillate at around twelve cycles per minute — close to the breathing rate of someone in deep sleep. Save this for tonight.",
    "soft_wind": f"Pink noise in wind sounds is linked to better memory consolidation during sleep. Your brain does not just rest — it recovers. Full version on Midnight Cabin.",
    "night_forest": f"Nature sounds reduce activity in the brain's threat detection centre. Your body stops bracing and starts resting. Save this for tonight.",
    "brown_noise": f"Brown noise shifts activity toward the prefrontal cortex — the part of the brain that struggles most with focus and impulse control. Full version on Midnight Cabin.",
}

FALLBACK_VOICEOVERS = {
    "pov": POV_VOICEOVERS_FALLBACK,
    "educational": EDUCATIONAL_VOICEOVERS_FALLBACK,
}

def generate_short_content(primary, hook_style, duration_label, theme, mood):
    """Use Claude to generate fresh hook text and voiceover."""
    anthropic_key = os.environ.get("ANTHROPIC_API_KEY", "")
    if not anthropic_key:
        print("ANTHROPIC_API_KEY not set — using fallback content")
        return None, None

    try:
        import anthropic as _anthropic
        import re as _re

        client = _anthropic.Anthropic(api_key=anthropic_key)

        prompt = f"""You are writing content for a YouTube Shorts video for @midnightcabins — a sleep and focus ambient sound channel.

This Short is a 60-second preview of a longer ambient video.

Theme: {theme}
Primary sound: {primary.replace("_", " ")}
Mood: {mood}
Full video duration: {duration_label}
Hook style: {hook_style}

Generate TWO things:

1. HOOK_TEXT — shown as large text on screen
   - Max 6 words, no punctuation except apostrophes
   - No emojis (they break video rendering)
   - Style guide:
     * POV style: Start with "POV:" then a short scene ("POV: The cabin is finally quiet")
     * Educational style: A short surprising fact or observation ("Rain masks every other sound")
   - Must feel natural when someone reads it in 2 seconds while scrolling
   - Do NOT use: exclamation marks, hashtags, all caps, generic phrases like "perfect sleep sounds"

2. VOICEOVER — spoken aloud by a calm female voice, max 30 words
   - Warm, intelligent, slightly poetic — like a thoughtful friend not a salesperson
   - Must feel complete in one breath
   - End with exactly one of these CTAs (pick the most natural fit):
     * "Full version on Midnight Cabin."
     * "Save this for tonight."
     * "Let the full version play later."
   - Do NOT mention: subscribe, like, comment, algorithm, YouTube
   - Do NOT start with "I" or "You"
   - POV style: immersive and sensory — describe what the listener feels or hears
   - Educational style: one specific insight about why this sound helps sleep or focus

Return ONLY valid JSON, no markdown:
{{"hook_text": "...", "voiceover": "..."}}"""

        response = client.messages.create(
            model="claude-haiku-4-5-20251001",
            max_tokens=200,
            temperature=0.9,
            messages=[{"role": "user", "content": prompt}]
        )

        text = response.content[0].text.strip()
        text = _re.sub(r"```json|```", "", text).strip()
        data = json.loads(text)

        hook = data.get("hook_text", "").strip()
        vo = data.get("voiceover", "").strip()

        # Validate
        if not hook or len(hook) > 60:
            print(f"LLM hook invalid: '{hook}' — using fallback")
            return None, None
        if not vo or len(vo.split()) > 40:
            print(f"LLM voiceover too long or empty — using fallback")
            return None, None

        print(f"LLM hook: {hook}")
        print(f"LLM voiceover: {vo[:60]}...")
        return hook, vo

    except Exception as e:
        print(f"LLM generation failed: {e} — using fallback")
        return None, None

# Generate via LLM
hook_text, voiceover_text = generate_short_content(
    primary, hook_style, duration_label, theme, mood
)

# Fallback to pre-written content if LLM fails
if not hook_text:
    hook_text = FALLBACK_HOOKS[hook_style].get(primary, "Save this sound for tonight")

if not voiceover_text:
    voiceover_text = FALLBACK_VOICEOVERS[hook_style].get(
        primary,
        f"{theme}. {duration_label} of uninterrupted ambient sound. Full version on Midnight Cabin."
    )

cta_text = random.choice([
    "Save this for tonight",
    f"Full {duration_label} on Midnight Cabin",
    "Let this play later",
])

# Strip emojis for drawtext (ffmpeg default font doesn't support emoji)
hook_text_display = strip_emojis(hook_text)
cta_text_display = strip_emojis(cta_text)

# ─────────────────────────────────────────────
# THEME-SPECIFIC START OFFSETS
# Best-sounding moment per theme
# ─────────────────────────────────────────────
START_OFFSETS = {
    "rain":         45,   # rain settles into rhythm at ~45s
    "fireplace":    30,   # crackles most present early on
    "river":        60,   # river flows consistently from 1min
    "ocean_waves":  90,   # waves establish their rhythm by 90s
    "soft_wind":    30,   # wind is fullest early
    "night_forest": 120,  # forest settles after 2min
    "brown_noise":  10,   # brown noise is consistent from the start
}

START_OFFSET = START_OFFSETS.get(primary, 60)
print(f"Starting Short at offset: {START_OFFSET}s")

# ─────────────────────────────────────────────
# GENERATE VOICEOVER via Google Cloud TTS
# ─────────────────────────────────────────────
def generate_voiceover(text, output_path):
    import urllib.request
    import urllib.error
    import base64
    import ssl

    # Fix macOS SSL cert verification
    ssl_context = ssl.create_default_context()
    try:
        import certifi
        ssl_context = ssl.create_default_context(cafile=certifi.where())
    except ImportError:
        ssl_context.check_hostname = False
        ssl_context.verify_mode = ssl.CERT_NONE

    api_key = os.environ.get("GOOGLE_TTS_API_KEY", "")

    if not api_key:
        print("GOOGLE_TTS_API_KEY not set — skipping voiceover")
        subprocess.run([
            "ffmpeg", "-y",
            "-f", "lavfi", "-i", "anullsrc=r=44100:cl=mono",
            "-t", "3", "-q:a", "9", "-acodec", "libmp3lame",
            output_path
        ], capture_output=True)
        return False

    payload = json.dumps({
        "input": {"text": text},
        "voice": {
            "languageCode": "en-US",
            "name": "en-US-Neural2-F",  # warm, natural female voice
            "ssmlGender": "FEMALE"
        },
        "audioConfig": {
            "audioEncoding": "MP3",
            "speakingRate": 0.95,
            "pitch": -1.0,
        }
    }).encode("utf-8")

    url = f"https://texttospeech.googleapis.com/v1/text:synthesize?key={api_key}"
    req = urllib.request.Request(
        url, data=payload,
        headers={"Content-Type": "application/json"}
    )

    try:
        with urllib.request.urlopen(req, timeout=30, context=ssl_context) as resp:
            result = json.loads(resp.read())
            audio_data = base64.b64decode(result["audioContent"])
            with open(output_path, "wb") as f:
                f.write(audio_data)
            print(f"Voiceover generated: {len(audio_data)} bytes")
            return True
    except Exception as e:
        print(f"TTS failed: {e}")
        subprocess.run([
            "ffmpeg", "-y",
            "-f", "lavfi", "-i", "anullsrc=r=44100:cl=mono",
            "-t", "3", "-q:a", "9", "-acodec", "libmp3lame",
            output_path
        ], capture_output=True)
        return False

has_voiceover = generate_voiceover(voiceover_text, VOICEOVER_PATH)

def get_duration(path):
    result = subprocess.run(
        ["ffprobe", "-v", "error", "-show_entries", "format=duration",
         "-of", "default=noprint_wrappers=1:nokey=1", path],
        capture_output=True, text=True
    )
    try:
        return float(result.stdout.strip())
    except Exception:
        return 3.0

vo_duration = get_duration(VOICEOVER_PATH) if os.path.exists(VOICEOVER_PATH) else 3.0
print(f"Voiceover duration: {vo_duration:.1f}s")

# ─────────────────────────────────────────────
# BUILD FILTER GRAPH
# ─────────────────────────────────────────────
def escape_text(text):
    return (text
        .replace("\\", "\\\\")
        .replace("'", "\\'")
        .replace(":", "\\:")
        .replace("%", "\\%")
        .replace("\n", "\\n"))

def wrap_text(text, width=24):
    words = text.split()
    lines, current, count = [], [], 0
    for word in words:
        if count + len(word) > width:
            lines.append(" ".join(current))
            current, count = [word], len(word)
        else:
            current.append(word)
            count += len(word) + 1
    if current:
        lines.append(" ".join(current))
    return "\\n".join(lines)

hook_wrapped = escape_text(wrap_text(hook_text_display, 22))
cta_escaped = escape_text(cta_text_display)
channel_escaped = escape_text("@midnightcabins")

hook_show_until = min(vo_duration + 2, 9)

# For contrast style — show silence label first 5s, then sound label
# ─────────────────────────────────────────────
# FONT SELECTION
# Uses best available font on current platform
# Falls back gracefully if font not found
# ─────────────────────────────────────────────

def find_font():
    """Find best available TTF font for the current platform."""
    system = platform.system()

    if system == "Darwin":  # macOS — use TTF only, avoid TTC
        mac_fonts = [
            "/System/Library/Fonts/Supplemental/Georgia.ttf",
            "/Library/Fonts/Arial.ttf",
            "/System/Library/Fonts/Supplemental/Verdana.ttf",
            "/System/Library/Fonts/Supplemental/Trebuchet MS.ttf",
        ]
        for path in mac_fonts:
            if os.path.exists(path):
                return path
        # Search user fonts
        user_fonts = os.path.expanduser("~/Library/Fonts")
        for f in ["Arial.ttf", "Helvetica.ttf", "Georgia.ttf"]:
            p = os.path.join(user_fonts, f)
            if os.path.exists(p):
                return p

    else:  # Linux / Railway (Debian trixie)
        linux_fonts = [
            "/usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf",
            "/usr/share/fonts/truetype/liberation2/LiberationSans-Regular.ttf",
            "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
            "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf",
            "/usr/share/fonts/opentype/noto/NotoSansCJK-Regular.ttc",
        ]
        for path in linux_fonts:
            if os.path.exists(path):
                return path

    return ""  # ffmpeg default font

FONT_FILE = find_font()
# Escape font path for ffmpeg filter string
font_path_escaped = FONT_FILE.replace("\\", "/").replace(":", "\\:").replace("'", "\\'") if FONT_FILE else ""
font_attr = f":fontfile='{font_path_escaped}'" if font_path_escaped else ""
print(f"Using font: {FONT_FILE or 'ffmpeg default'}")

# Build vf — no enable expressions to avoid ffmpeg comma parsing issues
# Hook shows full duration, CTA always visible at bottom
vf = (
    f"scale=1080:1920:force_original_aspect_ratio=increase,"
    f"crop=1080:1920,"
    f"drawtext=text='{hook_wrapped}'{font_attr}"
    f":fontsize=52:fontcolor=white"
    f":x=(w-text_w)/2:y=h/4"
    f":box=1:boxcolor=black@0.35:boxborderw=24"
    f","
    f"drawtext=text='{cta_escaped}'{font_attr}"
    f":fontsize=34:fontcolor=white"
    f":x=(w-text_w)/2:y=3*h/4"
    f":box=1:boxcolor=black@0.4:boxborderw=16"
    f","
    f"drawtext=text='{channel_escaped}'{font_attr}"
    f":fontsize=26:fontcolor=white@0.55"
    f":x=(w-text_w)/2:y=h-65,"
    f"format=yuv420p"
)

# ─────────────────────────────────────────────
# AUDIO — reveal effect + voiceover mix
# Audio fades from 20% to 100% over first 3 seconds
# giving a satisfying "sound reveal" feel
# For contrast style: near-silence for first 5s then full volume
# ─────────────────────────────────────────────
if not os.path.exists(SOURCE_VIDEO):
    raise FileNotFoundError(f"Main video not found: {SOURCE_VIDEO}")

# Audio reveal: simple fade-in using afade filter — universally compatible
# Fade from silence to full volume over 3 seconds
ambient_fade = "afade=t=in:st=0:d=3"

if has_voiceover and os.path.exists(VOICEOVER_PATH):
    filter_complex = (
        f"[0:a]{ambient_fade},volume=0.5[ambient];"
        f"[1:a]volume=1.1,adelay=300|300[vo];"
        f"[ambient][vo]amix=inputs=2:duration=first:weights=1 1[audio]"
    )
    cmd = [
        "ffmpeg", "-y",
        "-ss", str(START_OFFSET),
        "-t", str(SHORT_DURATION),
        "-i", SOURCE_VIDEO,
        "-i", VOICEOVER_PATH,
        "-filter_complex", filter_complex,
        "-vf", vf,
        "-map", "0:v",
        "-map", "[audio]",
        "-c:v", "libx264", "-preset", "fast", "-crf", "22",
        "-c:a", "aac", "-b:a", "192k",
        "-r", "30",
        "-movflags", "+faststart",
        SHORT_OUTPUT
    ]
else:
    cmd = [
        "ffmpeg", "-y",
        "-ss", str(START_OFFSET),
        "-t", str(SHORT_DURATION),
        "-i", SOURCE_VIDEO,
        "-vf", vf,
        "-af", f"{ambient_fade},volume=0.5",
        "-c:v", "libx264", "-preset", "fast", "-crf", "22",
        "-c:a", "aac", "-b:a", "192k",
        "-r", "30",
        "-movflags", "+faststart",
        SHORT_OUTPUT
    ]

print(f"Rendering Short ({hook_style} style)...")
result = subprocess.run(cmd, capture_output=True, text=True)

if result.returncode != 0:
    print("Short render failed:", result.stderr[-800:])
    raise RuntimeError("Short render failed")

print(f"Short rendered successfully: {SHORT_OUTPUT}")

# ─────────────────────────────────────────────
# SAVE METADATA
# ─────────────────────────────────────────────
short_meta = {
    "theme": theme,
    "primary": primary,
    "layers": layers,
    "mood": mood,
    "duration_label": duration_label,
    "hook_style": hook_style,
    "hook_text": hook_text,
    "is_flagship": bool(is_flagship),
    "flagship_short_plan": flagship_shorts,
    "voiceover_text": voiceover_text,
    "has_voiceover": has_voiceover,
    "start_offset": START_OFFSET,
    "created_at": datetime.now().isoformat(),
}

with open(os.path.join(PERSISTENT_DIR, "current_short.json"), "w") as f:
    json.dump(short_meta, f, indent=2)

print(f"Short metadata saved — style: {hook_style}, offset: {START_OFFSET}s")