"""
generate_short.py — YouTube Shorts generator for Midnight Cabin

Strategy:
- Rotates 3 hook styles: POV emotional / Educational / Contrast reveal
- Theme-specific start offsets for best-sounding moment
- Audio reveal: fades from 20% to 100% in first 3s for satisfying impact
- Vertical 1080x1920, 30fps, #Shorts format
"""

import json
import os
import platform
import random
import subprocess
from datetime import datetime

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PERSISTENT_DIR = os.environ.get("PERSISTENT_DIR", "/data")

# Short pipeline uses short_idea.json — decoupled from main pipeline
# SHORT_IDEA_PATH env var lets run_short_pipeline.sh specify it explicitly
_env_idea = os.environ.get("SHORT_IDEA_PATH", "")
if _env_idea and os.path.exists(_env_idea):
    IDEA_PATH = _env_idea
elif os.path.exists(os.path.join(PERSISTENT_DIR, "short_idea.json")):
    IDEA_PATH = os.path.join(PERSISTENT_DIR, "short_idea.json")
elif os.path.exists(os.path.join(PERSISTENT_DIR, "current_idea.json")):
    IDEA_PATH = os.path.join(PERSISTENT_DIR, "current_idea.json")
else:
    IDEA_PATH = os.path.join(BASE_DIR, "current_idea.json")

SOURCE_VIDEO = os.path.join(BASE_DIR, "output", "video.mp4")
BG_IMAGE = os.path.join(BASE_DIR, "video", "bg.jpg")
BG_ANIMATED = os.path.join(BASE_DIR, "video", "bg_animated.mp4")
SHORT_OUTPUT = os.path.join(BASE_DIR, "output", "short.mp4")
VOICEOVER_PATH = os.path.join(BASE_DIR, "output", "voiceover.mp3")
SHORT_ROTATION_FILE = os.path.join(PERSISTENT_DIR, "short_hook_rotation.json")

SHORT_DURATION = 28  # Under 30s gets stronger algorithmic push in Shorts feed

# ─────────────────────────────────────────────
# LOAD IDEA
# ─────────────────────────────────────────────
with open(IDEA_PATH) as f:
    idea = json.load(f)

theme = idea.get("theme", "Ambient Soundscape")
layers = idea.get("sound_layers", ["brown_noise"])
primary = idea.get("audio_strategy", {}).get("primary_category", "brown_noise")
mood = idea.get("audio_strategy", {}).get("mood", "calm")
duration_minutes = idea.get("duration_minutes", 480)
duration_label = "10 Hours" if duration_minutes >= 600 else "8 Hours"

def strip_emojis(text):
    """Remove emojis — ffmpeg drawtext doesn't support them without emoji font."""
    import re
    emoji_pattern = re.compile(
        "["
        "😀-🙏"
        "🌀-🗿"
        "🚀-🛿"
        "🇠-🇿"
        "✀-➿"
        "🤀-🧿"
        "☀-⛿"
        "🨀-🩯"
        "🩰-🫿"
        "]+",
        flags=re.UNICODE
    )
    return emoji_pattern.sub("", text).strip()

is_flagship = idea.get("is_flagship") or idea.get("content_tier") == "flagship"
flagship_shorts = (idea.get("flagship_package", {}) or {}).get("shorts", [])
print(f"Generating Short for: {theme} ({primary}) | flagship={is_flagship}")

# ─────────────────────────────────────────────
# HOOK ROTATION — cycles POV → Educational → Contrast
# ─────────────────────────────────────────────
"""
SHORT FORMATS — 5 distinct experiences that rotate.
Each is a different psychological mechanism, not just different text.

THE DROP      — 1.5s near-silence, then sound hits full. Relief contrast.
THE COUNTDOWN — Challenge timer. Participation bait. Save-trigger format.
THE REVEAL    — Screen starts dark, brightens slowly. Curiosity + immersion.
THE FACT      — One brain-science sentence, word by word. Educational dopamine.
THE SCENE     — Pure sound, no text for 18s, then one line fades in. Presence.
"""

SHORT_FORMATS = ["drop", "countdown", "reveal", "fact", "scene"]

rotation_data = {}
if os.path.exists(SHORT_ROTATION_FILE):
    with open(SHORT_ROTATION_FILE) as f:
        rotation_data = json.load(f)

last_format = rotation_data.get("last_format", "scene")
idx = SHORT_FORMATS.index(last_format) if last_format in SHORT_FORMATS else -1
hook_style = SHORT_FORMATS[(idx + 1) % len(SHORT_FORMATS)]

with open(SHORT_ROTATION_FILE, "w") as f:
    json.dump({"last_format": hook_style, "last_style": hook_style}, f)

print(f"Short format this run: {hook_style}")

# ─────────────────────────────────────────────
# HOOK TEXT + VOICEOVER — generated by Claude
# ─────────────────────────────────────────────

SOFT_CTAS = [
    "Save this for tonight.",
    "Save this for 3am.",
    "Save for when thoughts are loud.",
]

# ─────────────────────────────────────────────
# FORMAT-SPECIFIC FALLBACK CONTENT
# Each format has its own hook text and voiceover logic.
# LLM generates these fresh — fallbacks used only if API fails.
# ─────────────────────────────────────────────

# THE DROP — contrast between silence and arrival
DROP_HOOKS = {
    "rain":         "Wait for it",
    "fireplace":    "Wait for it",
    "river":        "Wait for it",
    "ocean_waves":  "Wait for it",
    "brown_noise":  "Wait for it",
    "soft_wind":    "Wait for it",
    "night_forest": "Wait for it",
    "thunder":      "Wait for it",
}
DROP_VOICEOVERS = {
    "rain":         "There it is. That exhale your body has been waiting for. Save this for tonight.",
    "fireplace":    "There it is. The warmth your nervous system needed. Save this for tonight.",
    "river":        "There it is. Something to follow that isn't your own thoughts. Save this for tonight.",
    "ocean_waves":  "There it is. The oldest sound your brain knows how to rest in. Save this for tonight.",
    "brown_noise":  "There it is. Your brain just stopped scanning. Save this for when thoughts are loud.",
    "soft_wind":    "There it is. Nothing needs you right now. Save this for tonight.",
    "night_forest": "There it is. Your nervous system just decided you are safe. Save this for tonight.",
    "thunder":      "There it is. Permission to stop doing things. Save this for tonight.",
}

# THE COUNTDOWN — challenge format, participation bait
COUNTDOWN_HOOKS = {
    "rain":         "Try not to relax",
    "fireplace":    "Stay tense. Go.",
    "river":        "Try not to exhale",
    "ocean_waves":  "Stay awake. Go.",
    "brown_noise":  "Keep one anxious thought",
    "soft_wind":    "Stay stressed. Go.",
    "night_forest": "Try not to feel safe",
    "thunder":      "Try not to feel cozy",
}
COUNTDOWN_VOICEOVERS = {
    "rain":         "Drop a candle below if you failed. Full version on Midnight Cabin.",
    "fireplace":    "Drop a candle below if you failed. Full version on Midnight Cabin.",
    "river":        "Drop a candle below if you failed. Full version on Midnight Cabin.",
    "ocean_waves":  "Drop a candle below if you failed. Full version on Midnight Cabin.",
    "brown_noise":  "Drop a candle below if your brain went quiet. Full version on Midnight Cabin.",
    "soft_wind":    "Drop a candle below if you failed. Full version on Midnight Cabin.",
    "night_forest": "Drop a candle below if you failed. Full version on Midnight Cabin.",
    "thunder":      "Drop a candle below if you failed. Full version on Midnight Cabin.",
}

# THE REVEAL — slow brightness reveal, curiosity pull
REVEAL_HOOKS = {
    "rain":         "Can you hear it",
    "fireplace":    "Can you feel it",
    "river":        "Can you hear it",
    "ocean_waves":  "Can you hear it",
    "brown_noise":  "Can you feel it",
    "soft_wind":    "Can you feel it",
    "night_forest": "Can you hear it",
    "thunder":      "Can you feel it",
}
REVEAL_VOICEOVERS = {
    "rain":         "Your brain heard it before you did. Save this for tonight.",
    "fireplace":    "Your nervous system felt it before you noticed. Save this for tonight.",
    "river":        "Your brain followed it before you decided to. Save this for tonight.",
    "ocean_waves":  "Your breathing slowed before you realised. Save this for tonight.",
    "brown_noise":  "Your brain stopped scanning before you asked it to. Save this for when thoughts are loud.",
    "soft_wind":    "Your shoulders dropped before you noticed. Save this for tonight.",
    "night_forest": "Your body decided you were safe before your mind caught up. Save this for tonight.",
    "thunder":      "Your body knew it was cozy before you thought it. Save this for tonight.",
}

# THE FACT — word-by-word sentence reveal, educational dopamine
FACT_HOOKS = {
    "rain":         "Why your brain loves this",
    "fireplace":    "Why fire feels like safety",
    "river":        "Why rivers quiet loud brains",
    "ocean_waves":  "Why waves are your oldest cue",
    "brown_noise":  "Why this stops the scanning",
    "soft_wind":    "Why wind feels like nothing needs you",
    "night_forest": "Why forests lower your threat response",
    "thunder":      "Why storms feel like permission",
}
FACT_VOICEOVERS = {
    "rain":         "Steady rain raises your auditory noise floor. Sudden sounds blend in. Your brain stops scanning for threats. That is why it works. Save this for tonight.",
    "fireplace":    "Irregular crackling keeps your auditory cortex just engaged enough to block intrusive thoughts. Not enough to keep you awake. Save this for tonight.",
    "river":        "Pink noise in flowing water matches your brain's own resting rhythms. Your mind recognises it and slows to match. Save this for tonight.",
    "ocean_waves":  "Ocean waves arrive at twelve cycles per minute. Almost exactly the breathing rate of deep sleep. Your body takes the cue. Save this for tonight.",
    "brown_noise":  "Brown noise shifts neural activity toward your prefrontal cortex. The part that struggles most with anxious loops. Save this for when thoughts are loud.",
    "soft_wind":    "Wind sounds contain pink noise — the same frequency profile as your brain's resting state. You feel calm before you decide to. Save this for tonight.",
    "night_forest": "Nature sounds reduce amygdala activity. Your brain's threat centre goes quiet. Your body stops bracing. That is what rest actually feels like. Save this for tonight.",
    "thunder":      "Thunderstorms mask environmental sounds that keep your brain on alert. The rumble replaces the silence your nervous system keeps checking. Save this for tonight.",
}

# THE SCENE — pure immersion, text appears late
SCENE_HOOKS = {
    # These appear at second 20 — after 20s of pure sound and visual
    "rain":         "You found the cabin",
    "fireplace":    "You found the cabin",
    "river":        "You found the cabin",
    "ocean_waves":  "You found the cabin",
    "brown_noise":  "Your brain just stopped",
    "soft_wind":    "You found the cabin",
    "night_forest": "You found the cabin",
    "thunder":      "You found the cabin",
}
SCENE_VOICEOVERS = {
    # No voiceover for scene format — pure audio immersion
    "rain":         "",
    "fireplace":    "",
    "river":        "",
    "ocean_waves":  "",
    "brown_noise":  "",
    "soft_wind":    "",
    "night_forest": "",
    "thunder":      "",
}

FORMAT_HOOKS = {
    "drop":      DROP_HOOKS,
    "countdown": COUNTDOWN_HOOKS,
    "reveal":    REVEAL_HOOKS,
    "fact":      FACT_HOOKS,
    "scene":     SCENE_HOOKS,
}
FORMAT_VOICEOVERS = {
    "drop":      DROP_VOICEOVERS,
    "countdown": COUNTDOWN_VOICEOVERS,
    "reveal":    REVEAL_VOICEOVERS,
    "fact":      FACT_VOICEOVERS,
    "scene":     SCENE_VOICEOVERS,
}

FALLBACK_HOOKS     = FORMAT_HOOKS
FALLBACK_VOICEOVERS = FORMAT_VOICEOVERS

def generate_short_content(primary, hook_style, duration_label, theme, mood):
    """Use Claude to generate fresh hook text and voiceover."""
    anthropic_key = os.environ.get("ANTHROPIC_API_KEY", "")
    if not anthropic_key:
        print("ANTHROPIC_API_KEY not set — using fallback content")
        return None, None

    try:
        import anthropic as _anthropic
        import re as _re

        client = _anthropic.Anthropic(api_key=anthropic_key)

        # Load recently used hooks to avoid repeats
        hooks_log_path = os.path.join(PERSISTENT_DIR, "used_hooks.json")
        used_hooks = []
        try:
            if os.path.exists(hooks_log_path):
                with open(hooks_log_path) as f:
                    used_hooks = json.load(f).get(primary, [])[-10:]
        except Exception:
            pass

        recent_hooks_str = (
            "\nAvoid these recently used hook texts (do NOT repeat them):\n" +
            "\n".join(f"- {h}" for h in used_hooks)
        ) if used_hooks else ""

        prompt = f"""You are writing content for a YouTube Short for @midnightcabins — a sleep/focus ambient channel.
The channel's top video: "Why your brain loves rain at night" — emotional recognition beats utility labels.

Sound: {primary.replace("_", " ")} | Mood: {mood} | Theme: {theme} | Full video: {duration_label}
Format: {hook_style}{recent_hooks_str}

{"FORMAT — THE DROP: 1.5s near-silence then sound arrives full. Hook = 3 words max, creates anticipation ('Wait for it'). Voiceover plays after sound hits (~3s) — describe the relief of arrival. End: 'Save this for tonight.'" if hook_style == "drop" else ""}
{"FORMAT — THE COUNTDOWN: Viewer tries to resist relaxing for 28 seconds. Hook = short imperative challenge. Voiceover at end asks them to comment if they failed. End: 'Drop a candle below if you failed.'" if hook_style == "countdown" else ""}
{"FORMAT — THE REVEAL: Screen starts dark, brightens slowly. Hook = short curiosity question ('Can you hear it'). Voiceover: their body responded before their mind did. End: 'Save this for tonight.'" if hook_style == "reveal" else ""}
{"FORMAT — THE FACT: One real brain-science sentence about WHY this sound works. Hook = 'Why your brain [X]'. Voiceover = the actual mechanism, specific, 2-3 sentences. End: 'Save this for tonight.'" if hook_style == "fact" else ""}
{"FORMAT — THE SCENE: NO voiceover (return empty string). Hook text appears at 20s after pure immersion. Hook = very short, poetic, present-tense ('You found the cabin'). Voiceover MUST be empty." if hook_style == "scene" else ""}

RULES: Hook max 5 words, no punctuation except apostrophes, no emojis. The word 'your' must appear.
Voiceover max 35 words (40 for fact). Warm and specific — like a friend at midnight, not a brand.
Never say: subscribe, like, Midnight Cabin (in voiceover), algorithm, YouTube.

Return ONLY valid JSON:
{{"hook_text": "...", "voiceover": "..."}}"""

        response = client.messages.create(
            model="claude-haiku-4-5-20251001",
            max_tokens=200,
            temperature=0.9,
            messages=[{"role": "user", "content": prompt}]
        )

        text = response.content[0].text.strip()
        text = _re.sub(r"```json|```", "", text).strip()
        data = json.loads(text)

        hook = data.get("hook_text", "").strip()
        vo = data.get("voiceover", "").strip()

        # Validate
        if not hook or len(hook) > 45:
            print(f"LLM hook too long ({len(hook)} chars): '{hook}' — using fallback")
            return None, None
        if not vo or len(vo.split()) > 40:
            print(f"LLM voiceover too long or empty — using fallback")
            return None, None

        print(f"LLM hook: {hook}")
        print(f"LLM voiceover: {vo[:60]}...")

        # Save hook to used log to prevent repeats in future runs
        try:
            hooks_log_path = os.path.join(PERSISTENT_DIR, "used_hooks.json")
            all_hooks = {}
            if os.path.exists(hooks_log_path):
                with open(hooks_log_path) as f:
                    all_hooks = json.load(f)
            niche_hooks = all_hooks.get(primary, [])
            if hook not in niche_hooks:
                niche_hooks.append(hook)
            all_hooks[primary] = niche_hooks[-20:]  # keep last 20 per niche
            with open(hooks_log_path, "w") as f:
                json.dump(all_hooks, f, indent=2)
        except Exception:
            pass

        return hook, vo

    except Exception as e:
        print(f"LLM generation failed: {e} — using fallback")
        return None, None

# Generate via LLM
hook_text, voiceover_text = generate_short_content(
    primary, hook_style, duration_label, theme, mood
)

# Fallback to pre-written content if LLM fails
if not hook_text:
    hook_text = FALLBACK_HOOKS[hook_style].get(primary, "Save this sound for tonight")

if not voiceover_text:
    voiceover_text = FALLBACK_VOICEOVERS[hook_style].get(
        primary,
        f"{theme}. {duration_label} of uninterrupted ambient sound. Full version on Midnight Cabin."
    )

cta_text = random.choice([
    "Save this for tonight",
    f"Full {duration_label} on Midnight Cabin",
    "Let this play later",
])

# Strip emojis for drawtext (ffmpeg default font doesn't support emoji)
hook_text_display = strip_emojis(hook_text)
cta_text_display = strip_emojis(cta_text)

# ─────────────────────────────────────────────
# THEME-SPECIFIC START OFFSETS
# Best-sounding moment per theme
# ─────────────────────────────────────────────
START_OFFSET_RANGES = {
    "rain":         (30,  180),
    "fireplace":    (20,  120),
    "river":        (45,  240),
    "ocean_waves":  (60,  300),
    "soft_wind":    (20,  150),
    "night_forest": (90,  300),
    "brown_noise":  (5,   120),
    "thunder":      (30,  180),
}
lo, hi = START_OFFSET_RANGES.get(primary, (30, 180))
START_OFFSET = random.randint(lo, hi)
print(f"Starting Short at offset: {START_OFFSET}s")

# ─────────────────────────────────────────────
# GENERATE VOICEOVER via Google Cloud TTS
# ─────────────────────────────────────────────
def generate_voiceover(text, output_path):
    import urllib.request
    import urllib.error
    import base64
    import ssl

    # Fix macOS SSL cert verification
    ssl_context = ssl.create_default_context()
    try:
        import certifi
        ssl_context = ssl.create_default_context(cafile=certifi.where())
    except ImportError:
        ssl_context.check_hostname = False
        ssl_context.verify_mode = ssl.CERT_NONE

    api_key = os.environ.get("GOOGLE_TTS_API_KEY", "")

    if not api_key:
        print("GOOGLE_TTS_API_KEY not set — skipping voiceover")
        subprocess.run([
            "ffmpeg", "-y",
            "-f", "lavfi", "-i", "anullsrc=r=44100:cl=mono",
            "-t", "3", "-q:a", "9", "-acodec", "libmp3lame",
            output_path
        ], capture_output=True)
        return False

    payload = json.dumps({
        "input": {"text": text},
        "voice": {
            "languageCode": "en-US",
            "name": "en-US-Neural2-F",  # warm, natural female voice
            "ssmlGender": "FEMALE"
        },
        "audioConfig": {
            "audioEncoding": "MP3",
            "speakingRate": 0.95,
            "pitch": -1.0,
        }
    }).encode("utf-8")

    url = f"https://texttospeech.googleapis.com/v1/text:synthesize?key={api_key}"
    req = urllib.request.Request(
        url, data=payload,
        headers={"Content-Type": "application/json"}
    )

    try:
        with urllib.request.urlopen(req, timeout=30, context=ssl_context) as resp:
            result = json.loads(resp.read())
            audio_data = base64.b64decode(result["audioContent"])
            with open(output_path, "wb") as f:
                f.write(audio_data)
            print(f"Voiceover generated: {len(audio_data)} bytes")
            return True
    except Exception as e:
        print(f"TTS failed: {e}")
        subprocess.run([
            "ffmpeg", "-y",
            "-f", "lavfi", "-i", "anullsrc=r=44100:cl=mono",
            "-t", "3", "-q:a", "9", "-acodec", "libmp3lame",
            output_path
        ], capture_output=True)
        return False

has_voiceover = generate_voiceover(voiceover_text, VOICEOVER_PATH)

def get_duration(path):
    result = subprocess.run(
        ["ffprobe", "-v", "error", "-show_entries", "format=duration",
         "-of", "default=noprint_wrappers=1:nokey=1", path],
        capture_output=True, text=True
    )
    try:
        return float(result.stdout.strip())
    except Exception:
        return 3.0

vo_duration = get_duration(VOICEOVER_PATH) if os.path.exists(VOICEOVER_PATH) else 3.0
print(f"Voiceover duration: {vo_duration:.1f}s")

# ─────────────────────────────────────────────
# BUILD FILTER GRAPH
# ─────────────────────────────────────────────
def escape_text(text):
    return (text
        .replace("\\", "\\\\")
        .replace("'", "\\'")
        .replace(":", "\\:")
        .replace("%", "\\%")
        .replace("\n", "\\n"))

# No wrapping — use single line with smaller font to avoid join typos
# LLM is instructed to keep hook under 6 words so it fits
hook_wrapped = escape_text(hook_text_display)
cta_escaped = escape_text(cta_text_display)
channel_escaped = escape_text("@midnightcabins")

hook_show_until = min(vo_duration + 2, 9)

# For contrast style — show silence label first 5s, then sound label
# ─────────────────────────────────────────────
# FONT SELECTION
# Uses best available font on current platform
# Falls back gracefully if font not found
# ─────────────────────────────────────────────

def find_font():
    """Find best available TTF font for the current platform."""
    system = platform.system()

    if system == "Darwin":  # macOS — use TTF only, avoid TTC
        mac_fonts = [
            "/System/Library/Fonts/Supplemental/Georgia.ttf",
            "/Library/Fonts/Arial.ttf",
            "/System/Library/Fonts/Supplemental/Verdana.ttf",
            "/System/Library/Fonts/Supplemental/Trebuchet MS.ttf",
        ]
        for path in mac_fonts:
            if os.path.exists(path):
                return path
        # Search user fonts
        user_fonts = os.path.expanduser("~/Library/Fonts")
        for f in ["Arial.ttf", "Helvetica.ttf", "Georgia.ttf"]:
            p = os.path.join(user_fonts, f)
            if os.path.exists(p):
                return p

    else:  # Linux / Railway (Debian trixie)
        linux_fonts = [
            "/usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf",
            "/usr/share/fonts/truetype/liberation2/LiberationSans-Regular.ttf",
            "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
            "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf",
            "/usr/share/fonts/opentype/noto/NotoSansCJK-Regular.ttc",
        ]
        for path in linux_fonts:
            if os.path.exists(path):
                return path

    return ""  # ffmpeg default font

FONT_FILE = find_font()
# Escape font path for ffmpeg filter string
font_path_escaped = FONT_FILE.replace("\\", "/").replace(":", "\\:").replace("'", "\\'") if FONT_FILE else ""
font_attr = f":fontfile='{font_path_escaped}'" if font_path_escaped else ""
print(f"Using font: {FONT_FILE or 'ffmpeg default'}")

# Niche audio EQ — each sound gets subtle frequency shaping
NICHE_AUDIO_EQ = {
    "rain":         "equalizer=f=200:width_type=o:width=2:g=1,equalizer=f=8000:width_type=o:width=2:g=-3",
    "fireplace":    "equalizer=f=100:width_type=o:width=2:g=3,equalizer=f=6000:width_type=o:width=2:g=-4",
    "river":        "equalizer=f=500:width_type=o:width=2:g=2,equalizer=f=8000:width_type=o:width=2:g=-2",
    "ocean_waves":  "equalizer=f=150:width_type=o:width=2:g=2,equalizer=f=7000:width_type=o:width=2:g=-3",
    "soft_wind":    "equalizer=f=300:width_type=o:width=2:g=1,equalizer=f=9000:width_type=o:width=2:g=-2",
    "night_forest": "equalizer=f=400:width_type=o:width=2:g=2,equalizer=f=8000:width_type=o:width=2:g=-2",
    "brown_noise":  "equalizer=f=100:width_type=o:width=2:g=2,equalizer=f=5000:width_type=o:width=2:g=-1",
    "thunder":      "equalizer=f=80:width_type=o:width=2:g=4,equalizer=f=8000:width_type=o:width=2:g=-5",
}
niche_eq = NICHE_AUDIO_EQ.get(primary, "")

# Format-specific audio treatment
if hook_style == "drop":
    # Near-silence for 1.5s, then hard hit to full volume
    # Creates the contrast that makes the drop feel satisfying
    ambient_fade = f"volume=enable='lt(t,1.5)':volume=0.04,afade=t=in:st=1.5:d=0.3,{niche_eq}" if niche_eq else "volume=enable='lt(t,1.5)':volume=0.04,afade=t=in:st=1.5:d=0.3"
elif hook_style == "scene":
    # Full volume from the start — pure immersion, no fade hesitation
    ambient_fade = f"afade=t=in:st=0:d=0.8,{niche_eq}" if niche_eq else "afade=t=in:st=0:d=0.8"
else:
    # Standard 2s fade for countdown, reveal, fact
    ambient_fade = f"afade=t=in:st=0:d=2,{niche_eq}" if niche_eq else "afade=t=in:st=0:d=2"

# Scene and countdown formats don't use voiceover
if hook_style in ("scene", "countdown"):
    has_voiceover = False

# Niche colour grades — each sound type gets a distinct visual feel
NICHE_COLOR_GRADE = {
    "rain":         "eq=contrast=1.05:saturation=0.75:brightness=-0.04,colorbalance=bs=0.04",
    "fireplace":    "eq=contrast=1.08:saturation=1.15:brightness=0.02,colorbalance=rs=0.06",
    "river":        "eq=contrast=1.04:saturation=0.85:brightness=-0.02,colorbalance=gs=0.03",
    "ocean_waves":  "eq=contrast=1.06:saturation=0.80:brightness=-0.03,colorbalance=bs=0.05",
    "soft_wind":    "eq=contrast=1.03:saturation=0.90:brightness=0.01",
    "night_forest": "eq=contrast=1.07:saturation=0.70:brightness=-0.05,colorbalance=gs=0.04",
    "brown_noise":  "eq=contrast=1.04:saturation=0.65:brightness=-0.03",
    "thunder":      "eq=contrast=1.10:saturation=0.60:brightness=-0.06,colorbalance=bs=0.03",
}
color_grade = NICHE_COLOR_GRADE.get(primary, "eq=contrast=1.04:saturation=0.85")

# ─────────────────────────────────────────────
# FORMAT-SPECIFIC VISUAL FILTER CHAINS
# Each format has a completely different visual treatment.
# This is what makes each Short look and feel distinct.
# ─────────────────────────────────────────────

def esc(text):
    return (text
        .replace("\\", "\\\\")
        .replace("'",  "\\'")
        .replace(":", "\\:")
        .replace("%",  "\\%")
        .replace("\n", " "))

hook_e    = esc(hook_text_display)
cta_e     = esc(cta_text_display)
handle_e  = esc("@midnightcabins")

if hook_style == "drop":
    # THE DROP — clean frame, no text until sound arrives at 1.5s
    # Hook fades IN at t=1.5s (when audio hits), fades out at t=8s
    # CTA fades in at t=20s
    hook_alpha = "if(lt(t,1.5),0,if(lt(t,3),((t-1.5)/1.5),if(lt(t,7),1,if(lt(t,9),((9-t)/2),0))))"
    cta_alpha  = "if(lt(t,20),0,if(lt(t,22),((t-20)/2),1))"
    vf = (
        f"scale=1080:1920:force_original_aspect_ratio=increase,crop=1080:1920,"
        f"{color_grade},"
        # Very slight vignette — dark edges pull focus to centre
        f"drawbox=x=0:y=0:w=iw:h=ih:color=black@0.18:t=60,"
        f"drawtext=text='{hook_e}'{font_attr}"
        f":fontsize=58:fontcolor=white"
        f":x=(w-text_w)/2:y=h/4"
        f":box=1:boxcolor=black@0.3:boxborderw=28"
        f":alpha='{hook_alpha}',"
        f"drawtext=text='{cta_e}'{font_attr}"
        f":fontsize=36:fontcolor=white"
        f":x=(w-text_w)/2:y=3*h/4+60"
        f":box=1:boxcolor=black@0.45:boxborderw=18"
        f":alpha='{cta_alpha}',"
        f"drawtext=text='{handle_e}'{font_attr}"
        f":fontsize=26:fontcolor=white@0.45"
        f":x=(w-text_w)/2:y=h-65,"
        f"format=yuv420p"
    )

elif hook_style == "countdown":
    # THE COUNTDOWN — massive timer centre-screen, challenge hook at top
    # Timer counts DOWN from SHORT_DURATION to 0
    # Comment bait fades in at t=20
    comment_e   = esc("Drop a candle if you failed")
    bait_alpha  = "if(lt(t,20),0,if(lt(t,22),((t-20)/2),1))"
    vf = (
        f"scale=1080:1920:force_original_aspect_ratio=increase,crop=1080:1920,"
        f"{color_grade},"
        # Challenge hook — top quarter, always visible
        f"drawtext=text='{hook_e}'{font_attr}"
        f":fontsize=52:fontcolor=white"
        f":x=(w-text_w)/2:y=140"
        f":box=1:boxcolor=black@0.4:boxborderw=24,"
        # Countdown timer — massive, centre stage
        f"drawtext=text='%{{eif\\:{SHORT_DURATION}-trunc(t)\\:d\\:2}}'{font_attr}"
        f":fontsize=210:fontcolor=white"
        f":x=(w-text_w)/2:y=(h-text_h)/2-60"
        f":shadowx=5:shadowy=5:shadowcolor=black@0.5,"
        # Comment bait fades in late
        f"drawtext=text='{comment_e}'{font_attr}"
        f":fontsize=38:fontcolor=white@0.9"
        f":x=(w-text_w)/2:y=3*h/4+40"
        f":box=1:boxcolor=black@0.4:boxborderw=16"
        f":alpha='{bait_alpha}',"
        f"drawtext=text='{handle_e}'{font_attr}"
        f":fontsize=26:fontcolor=white@0.45"
        f":x=(w-text_w)/2:y=h-65,"
        f"format=yuv420p"
    )

elif hook_style == "reveal":
    # THE REVEAL — screen starts dark, gradually brightens to normal over 12s
    # Uses eq=brightness with time expression for the dark-to-light ramp
    reveal_answer = {
        "rain":         "your body knew before you did",
        "fireplace":    "your body felt it before you did",
        "river":        "your mind followed before you decided",
        "ocean_waves":  "your breathing slowed before you noticed",
        "brown_noise":  "your brain stopped scanning before you asked",
        "soft_wind":    "your shoulders dropped before you noticed",
        "night_forest": "your body decided you were safe first",
        "thunder":      "your body knew it was cozy first",
    }
    answer_e     = esc(reveal_answer.get(primary, "your body knew before you did"))
    answer_alpha = "if(lt(t,14),0,if(lt(t,16),((t-14)/2),1))"
    cta_alpha    = "if(lt(t,22),0,if(lt(t,24),((t-22)/2),1))"
    # brightness ramp: -0.5 at t=0, reaches 0 at t=12, stable after
    # eq brightness range is -1 to 1; we go from -0.5 to 0
    brightness_expr = "if(lt(t\\,12)\\,-0.5+t/12*0.5\\,0)"
    vf = (
        f"scale=1080:1920:force_original_aspect_ratio=increase,crop=1080:1920,"
        f"{color_grade},"
        # Dynamic brightness reveal — eq supports expressions for brightness
        f"eq=brightness='{brightness_expr}',"
        # Hook question — visible throughout
        f"drawtext=text='{hook_e}'{font_attr}"
        f":fontsize=54:fontcolor=white"
        f":x=(w-text_w)/2:y=h/4"
        f":box=1:boxcolor=black@0.3:boxborderw=26,"
        # Answer fades in at 14s
        f"drawtext=text='{answer_e}'{font_attr}"
        f":fontsize=36:fontcolor=white@0.9"
        f":x=(w-text_w)/2:y=h/2+80"
        f":box=1:boxcolor=black@0.3:boxborderw=18"
        f":alpha='{answer_alpha}',"
        # CTA fades in at 22s
        f"drawtext=text='{cta_e}'{font_attr}"
        f":fontsize=36:fontcolor=white"
        f":x=(w-text_w)/2:y=3*h/4+80"
        f":box=1:boxcolor=black@0.4:boxborderw=18"
        f":alpha='{cta_alpha}',"
        f"drawtext=text='{handle_e}'{font_attr}"
        f":fontsize=26:fontcolor=white@0.45"
        f":x=(w-text_w)/2:y=h-65,"
        f"format=yuv420p"
    )

elif hook_style == "fact":
    # THE FACT — hook at top throughout, fact sentence appears word by word
    # Word reveal: each word fades in 1.8s apart starting at t=3
    # CTA at bottom fades in at t=22
    cta_alpha  = "if(lt(t,22),0,if(lt(t,24),((t-22)/2),1))"
    # Staggered word reveals using multiple drawtext with time-gated alphas
    fact_words = hook_text_display.split()[:8]  # max 8 words for the fact line
    word_filters = []
    for i, word in enumerate(fact_words):
        t_start = 2.5 + i * 1.6
        t_end   = t_start + 1.2
        w_alpha = f"if(lt(t,{t_start}),0,if(lt(t,{t_end}),(t-{t_start})/{t_end-t_start:.1f},1))"
        # Position words left-to-right approximately
        x_pos   = f"(w/2 - {len(' '.join(fact_words)) * 11})/2 + {i * (len(word) * 22 + 10)}"
        word_e  = esc(word)
        word_filters.append(
            f"drawtext=text='{word_e}'{font_attr}"
            f":fontsize=52:fontcolor=white"
            f":x={x_pos}:y=h/4"
            f":alpha='{w_alpha}'"
        )
    # Build simpler version — reveal full hook line at once but with fade
    hook_alpha = "if(lt(t,1),0,if(lt(t,3),((t-1)/2),1))"
    vf = (
        f"scale=1080:1920:force_original_aspect_ratio=increase,crop=1080:1920,"
        f"{color_grade},"
        f"drawbox=x=0:y=0:w=iw:h=ih:color=black@0.15:t=60,"
        # Hook fades in at top
        f"drawtext=text='{hook_e}'{font_attr}"
        f":fontsize=50:fontcolor=white"
        f":x=(w-text_w)/2:y=160"
        f":box=1:boxcolor=black@0.35:boxborderw=24"
        f":alpha='{hook_alpha}',"
        # Voiceover text summary — middle of screen, appears at t=5
        f"drawtext=text='{cta_e}'{font_attr}"
        f":fontsize=34:fontcolor=white"
        f":x=(w-text_w)/2:y=3*h/4+60"
        f":box=1:boxcolor=black@0.4:boxborderw=16"
        f":alpha='{cta_alpha}',"
        f"drawtext=text='{handle_e}'{font_attr}"
        f":fontsize=26:fontcolor=white@0.45"
        f":x=(w-text_w)/2:y=h-65,"
        f"format=yuv420p"
    )

else:  # scene
    # THE SCENE — pure immersion. No text for first 20 seconds.
    # Hook appears very late with a slow fade in.
    # No CTA text — just the handle. Minimalist.
    hook_alpha = "if(lt(t,20),0,if(lt(t,23),((t-20)/3),if(lt(t,26),1,if(lt(t,28),((28-t)/2),0))))"
    vf = (
        f"scale=1080:1920:force_original_aspect_ratio=increase,crop=1080:1920,"
        f"{color_grade},"
        # Subtle vignette for cinematic feel
        f"drawbox=x=0:y=0:w=iw:h=ih:color=black@0.22:t=55,"
        # Hook appears at 20s, disappears near end
        f"drawtext=text='{hook_e}'{font_attr}"
        f":fontsize=56:fontcolor=white"
        f":x=(w-text_w)/2:y=h/2-60"
        f":alpha='{hook_alpha}',"
        # Handle — barely visible, always present
        f"drawtext=text='{handle_e}'{font_attr}"
        f":fontsize=26:fontcolor=white@0.35"
        f":x=(w-text_w)/2:y=h-65,"
        f"format=yuv420p"
    )

# ─────────────────────────────────────────────
# PICK VIDEO SOURCE — portrait-first for Shorts
#
# Priority order:
#   1. bg_short_animated.mp4 — dedicated vertical animation (best)
#   2. bg_short.jpg           — portrait still image (good)
#   3. bg_animated.mp4        — landscape animation (crops to vertical)
#   4. Library portrait image — still, correct orientation
#   5. Library landscape image — still, cropped to vertical
#   6. source video.mp4       — last resort
# ─────────────────────────────────────────────
LIBRARY_DIR = os.path.join(BASE_DIR, "video", "library")

def pick_library_image_for_niche(niche):
    # Check portrait subfolder first
    portrait_folder = os.path.join(LIBRARY_DIR, niche, "portrait")
    landscape_folder = os.path.join(LIBRARY_DIR, niche)
    folder = portrait_folder if os.path.exists(portrait_folder) else landscape_folder
    if not os.path.exists(folder):
        folder = LIBRARY_DIR
    if not os.path.exists(folder):
        return None
    images = [os.path.join(folder, f) for f in os.listdir(folder)
              if f.lower().endswith((".jpg", ".jpeg", ".png"))]
    return random.choice(images) if images else None

# Check all sources in priority order
SHORT_BG_VIDEO_PATH = os.path.join(BASE_DIR, "video", "bg_short_animated.mp4")
SHORT_BG_IMAGE_PATH = os.path.join(BASE_DIR, "video", "bg_short.jpg")
PERSISTENT_SHORT_ANIM = os.path.join(PERSISTENT_DIR, "bg_short_animated.mp4")

BG_ANIMATED_PERSISTENT = os.path.join(PERSISTENT_DIR, "bg_animated.mp4")
VISUAL_META_PATH = os.path.join(PERSISTENT_DIR, "current_visual.json")
SHORT_VISUAL_META_PATH = os.path.join(PERSISTENT_DIR, "current_short_visual.json")

animated_niche = None
short_visual_is_portrait = False
short_visual_niche = None

# Read short visual meta — check niche matches current idea
try:
    if os.path.exists(SHORT_VISUAL_META_PATH):
        with open(SHORT_VISUAL_META_PATH) as _f: _svm = json.load(_f)
        short_visual_niche = _svm.get("primary") or _svm.get("primary_category")
        niche_matches = (short_visual_niche == primary)
        short_visual_is_portrait = _svm.get("portrait", False) and niche_matches
        if not niche_matches:
            print(f"⚠️  Short visual niche mismatch: stored={short_visual_niche}, current={primary}")
            print(f"   Clearing stale visual assets so correct niche is used...")
            # Delete stale portrait assets so we don't accidentally use wrong-niche visuals
            for stale in [SHORT_BG_VIDEO_PATH, SHORT_BG_IMAGE_PATH,
                          os.path.join(PERSISTENT_DIR, "bg_short_animated.mp4")]:
                if os.path.exists(stale):
                    os.remove(stale)
                    print(f"   Removed: {stale}")
except Exception:
    pass

# Read main visual meta
try:
    if os.path.exists(VISUAL_META_PATH):
        with open(VISUAL_META_PATH) as _vmf: _vm = json.load(_vmf)
        animated_niche = _vm.get("primary") or _vm.get("primary_category")
except Exception:
    pass

print(f"DEBUG — Niche: {primary} | Short visual niche: {short_visual_niche} | Main animated niche: {animated_niche}")
print(f"DEBUG — Short video source check:")
print(f"  bg_short_animated (app):        {SHORT_BG_VIDEO_PATH} — {os.path.exists(SHORT_BG_VIDEO_PATH)}")
print(f"  bg_short_animated (persistent): {PERSISTENT_SHORT_ANIM} — {os.path.exists(PERSISTENT_SHORT_ANIM)}")
print(f"  bg_short.jpg:                   {SHORT_BG_IMAGE_PATH} — {os.path.exists(SHORT_BG_IMAGE_PATH)}")
print(f"  bg_animated (main):             {BG_ANIMATED} — {os.path.exists(BG_ANIMATED)}")
print(f"  source video:                   {SOURCE_VIDEO} — {os.path.exists(SOURCE_VIDEO)}")

# ── PRIORITY ORDER (all with niche checks) ──────────────────────
# 1. Dedicated portrait Short animation — niche verified via meta
if os.path.exists(SHORT_BG_VIDEO_PATH) and short_visual_is_portrait:
    print(f"✅ Using dedicated portrait Short animation (niche={primary})")
    SHORT_VIDEO_SOURCE = SHORT_BG_VIDEO_PATH
    USE_LOOP = True

# 2. Persistent portrait Short animation — niche verified via meta
elif os.path.exists(PERSISTENT_SHORT_ANIM) and short_visual_is_portrait:
    print(f"✅ Using persistent portrait Short animation (niche={primary})")
    import shutil as _sh
    _sh.copy(PERSISTENT_SHORT_ANIM, SHORT_BG_VIDEO_PATH)
    SHORT_VIDEO_SOURCE = SHORT_BG_VIDEO_PATH
    USE_LOOP = True

# 3. Portrait still image — ONLY if niche matches
elif os.path.exists(SHORT_BG_IMAGE_PATH) and short_visual_niche == primary:
    print(f"✅ Using portrait Short still image (niche={primary})")
    STATIC_BG = os.path.join(BASE_DIR, "output", "short_bg_static.mp4")
    static_result = subprocess.run([
        "ffmpeg", "-y", "-loop", "1", "-i", SHORT_BG_IMAGE_PATH,
        "-t", str(SHORT_DURATION + 5),
        "-vf", f"scale=1080:1920:force_original_aspect_ratio=increase,crop=1080:1920,{color_grade},format=yuv420p",
        "-c:v", "libx264", "-preset", "ultrafast", "-crf", "28", "-r", "30", STATIC_BG
    ], capture_output=True, text=True)
    SHORT_VIDEO_SOURCE = STATIC_BG if static_result.returncode == 0 else None
    USE_LOOP = static_result.returncode == 0

# 4. Main animated bg — ONLY if niche matches
elif os.path.exists(BG_ANIMATED) and animated_niche == primary:
    print(f"✅ Using main animated bg (niche={primary})")
    SHORT_VIDEO_SOURCE = BG_ANIMATED
    USE_LOOP = True

# 5. Persistent main animated bg — ONLY if niche matches
elif os.path.exists(BG_ANIMATED_PERSISTENT) and animated_niche == primary:
    print(f"✅ Using persistent main animated bg (niche={primary})")
    SHORT_VIDEO_SOURCE = BG_ANIMATED_PERSISTENT
    import shutil as _shutil2
    _shutil2.copy(BG_ANIMATED_PERSISTENT, BG_ANIMATED)
    USE_LOOP = True

# 6. Library image for THIS niche (correct niche guaranteed)
else:
    library_image = pick_library_image_for_niche(primary)
    if library_image:
        print(f"✅ Using library image for '{primary}': {os.path.basename(library_image)}")
        STATIC_BG = os.path.join(BASE_DIR, "output", "short_bg_static.mp4")
        static_result = subprocess.run([
            "ffmpeg", "-y", "-loop", "1", "-i", library_image,
            "-t", str(SHORT_DURATION + 5),
            "-vf", f"scale=1080:1920:force_original_aspect_ratio=increase,crop=1080:1920,{color_grade},format=yuv420p",
            "-c:v", "libx264", "-preset", "ultrafast", "-crf", "28", "-r", "30", STATIC_BG
        ], capture_output=True, text=True)
        SHORT_VIDEO_SOURCE = STATIC_BG if static_result.returncode == 0 else None
        USE_LOOP = static_result.returncode == 0
    else:
        SHORT_VIDEO_SOURCE = None
        USE_LOOP = False
        # No image available — generate a minimal black frame with colour overlay
        print("No visual source found — generating minimal procedural visual")
        STATIC_BG = os.path.join(BASE_DIR, "output", "short_bg_static.mp4")
        NICHE_COLORS = {
            "rain":         "0x0a1520",
            "fireplace":    "0x1a0a00",
            "river":        "0x051510",
            "ocean_waves":  "0x050a1a",
            "soft_wind":    "0x080f08",
            "night_forest": "0x050f05",
            "brown_noise":  "0x0a0a0a",
            "thunder":      "0x05050f",
        }
        bg_color = NICHE_COLORS.get(primary, "0x080808")
        proc_result = subprocess.run([
            "ffmpeg", "-y",
            "-f", "lavfi", "-i", f"color=c={bg_color}:size=1080x1920:rate=30",
            "-t", str(SHORT_DURATION + 5),
            "-vf", f"{color_grade},format=yuv420p",
            "-c:v", "libx264", "-preset", "ultrafast", "-crf", "28", STATIC_BG
        ], capture_output=True, text=True)
        if proc_result.returncode == 0:
            SHORT_VIDEO_SOURCE = STATIC_BG
            USE_LOOP = True
        else:
            raise RuntimeError(f"Procedural fallback render failed: {proc_result.stderr[-200:]}")

# ─────────────────────────────────────────────
# AUDIO SOURCE SELECTION
# Short's own audio (short_audio.wav) takes priority.
# Falls back to main video.mp4 only if wav doesn't exist.
# ─────────────────────────────────────────────
SHORT_AUDIO = os.path.join(BASE_DIR, "audio", "short_audio.wav")
if os.path.exists(SHORT_AUDIO):
    AUDIO_SOURCE  = SHORT_AUDIO
    AUDIO_IS_WAV  = True
    AUDIO_SS_FLAG = []  # WAV: no seek needed, use from beginning
    print(f"✅ Using Short audio: {SHORT_AUDIO}")
elif os.path.exists(SOURCE_VIDEO):
    AUDIO_SOURCE  = SOURCE_VIDEO
    AUDIO_IS_WAV  = False
    AUDIO_SS_FLAG = ["-ss", str(START_OFFSET)]
    print(f"Using main video audio (fallback): {SOURCE_VIDEO}")
else:
    raise RuntimeError(
        "No audio source found. "
        "Run generate_short_audio.py first, or ensure output/video.mp4 exists."
    )

if USE_LOOP:
    if has_voiceover and os.path.exists(VOICEOVER_PATH):
        filter_complex = (
            f"[1:a]{ambient_fade},volume=0.5[ambient];"
            f"[2:a]volume=1.1,adelay=300|300[vo];"
            f"[ambient][vo]amix=inputs=2:duration=first:weights=1 1[audio]"
        )
        cmd = (
            ["ffmpeg", "-y",
             "-stream_loop", "-1", "-i", SHORT_VIDEO_SOURCE]
            + AUDIO_SS_FLAG
            + ["-t", str(SHORT_DURATION), "-i", AUDIO_SOURCE,
               "-i", VOICEOVER_PATH,
               "-t", str(SHORT_DURATION),
               "-filter_complex", filter_complex,
               "-vf", vf,
               "-map", "0:v", "-map", "[audio]",
               "-c:v", "libx264", "-preset", "fast", "-crf", "22",
               "-c:a", "aac", "-b:a", "192k",
               "-r", "30", "-movflags", "+faststart",
               SHORT_OUTPUT]
        )
    else:
        cmd = (
            ["ffmpeg", "-y",
             "-stream_loop", "-1", "-i", SHORT_VIDEO_SOURCE]
            + AUDIO_SS_FLAG
            + ["-t", str(SHORT_DURATION), "-i", AUDIO_SOURCE,
               "-t", str(SHORT_DURATION),
               "-vf", vf,
               "-map", "0:v", "-map", "1:a",
               "-af", f"{ambient_fade},volume=0.5",
               "-c:v", "libx264", "-preset", "fast", "-crf", "22",
               "-c:a", "aac", "-b:a", "192k",
               "-r", "30", "-movflags", "+faststart",
               SHORT_OUTPUT]
        )
elif has_voiceover and os.path.exists(VOICEOVER_PATH):
    filter_complex = (
        f"[0:a]{ambient_fade},volume=0.5[ambient];"
        f"[1:a]volume=1.1,adelay=300|300[vo];"
        f"[ambient][vo]amix=inputs=2:duration=first:weights=1 1[audio]"
    )
    cmd = (
        ["ffmpeg", "-y"]
        + AUDIO_SS_FLAG
        + ["-t", str(SHORT_DURATION), "-i", SHORT_VIDEO_SOURCE,
           "-i", VOICEOVER_PATH,
           "-filter_complex", filter_complex,
           "-vf", vf,
           "-map", "0:v", "-map", "[audio]",
           "-c:v", "libx264", "-preset", "fast", "-crf", "22",
           "-c:a", "aac", "-b:a", "192k",
           "-r", "30", "-movflags", "+faststart",
           SHORT_OUTPUT]
    )
else:
    cmd = (
        ["ffmpeg", "-y"]
        + AUDIO_SS_FLAG
        + ["-t", str(SHORT_DURATION), "-i", SHORT_VIDEO_SOURCE,
           "-i", AUDIO_SOURCE,
           "-t", str(SHORT_DURATION),
           "-vf", vf,
           "-map", "0:v", "-map", "1:a",
           "-af", f"{ambient_fade},volume=0.5",
           "-c:v", "libx264", "-preset", "fast", "-crf", "22",
           "-c:a", "aac", "-b:a", "192k",
           "-r", "30", "-movflags", "+faststart",
           SHORT_OUTPUT]
    )

print(f"Rendering Short ({hook_style} style)...")
result = subprocess.run(cmd, capture_output=True, text=True)

if result.returncode != 0:
    print("Short render failed:", result.stderr[-800:])
    raise RuntimeError("Short render failed")

print(f"Short rendered successfully: {SHORT_OUTPUT}")

# ─────────────────────────────────────────────
# SAVE METADATA
# ─────────────────────────────────────────────
short_meta = {
    "theme": theme,
    "primary": primary,
    "layers": layers,
    "mood": mood,
    "duration_label": duration_label,
    "hook_style": hook_style,
    "hook_text": hook_text,
    "is_flagship": bool(is_flagship),
    "flagship_short_plan": flagship_shorts,
    "voiceover_text": voiceover_text,
    "has_voiceover": has_voiceover,
    "start_offset": START_OFFSET,
    "created_at": datetime.now().isoformat(),
}

with open(os.path.join(PERSISTENT_DIR, "current_short.json"), "w") as f:
    json.dump(short_meta, f, indent=2)

print(f"Short metadata saved — style: {hook_style}, offset: {START_OFFSET}s")