"""
generate_short.py — YouTube Shorts generator for Midnight Cabin

Strategy:
- Rotates 3 hook styles: POV emotional / Educational / Contrast reveal
- Theme-specific start offsets for best-sounding moment
- Audio reveal: fades from 20% to 100% in first 3s for satisfying impact
- Vertical 1080x1920, 30fps, #Shorts format
"""

import json
import os
import platform
import random
import subprocess
from datetime import datetime

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PERSISTENT_DIR = os.environ.get("PERSISTENT_DIR", "/data")

IDEA_PATH = os.path.join(PERSISTENT_DIR, "current_idea.json")
if not os.path.exists(IDEA_PATH):
    IDEA_PATH = os.path.join(BASE_DIR, "current_idea.json")

SOURCE_VIDEO = os.path.join(BASE_DIR, "output", "video.mp4")
BG_IMAGE = os.path.join(BASE_DIR, "video", "bg.jpg")
BG_ANIMATED = os.path.join(BASE_DIR, "video", "bg_animated.mp4")
SHORT_OUTPUT = os.path.join(BASE_DIR, "output", "short.mp4")
VOICEOVER_PATH = os.path.join(BASE_DIR, "output", "voiceover.mp3")
SHORT_ROTATION_FILE = os.path.join(PERSISTENT_DIR, "short_hook_rotation.json")

SHORT_DURATION = 28  # Under 30s gets stronger algorithmic push in Shorts feed

# ─────────────────────────────────────────────
# LOAD IDEA
# ─────────────────────────────────────────────
with open(IDEA_PATH) as f:
    idea = json.load(f)

theme = idea.get("theme", "Ambient Soundscape")
layers = idea.get("sound_layers", ["brown_noise"])
primary = idea.get("audio_strategy", {}).get("primary_category", "brown_noise")
mood = idea.get("audio_strategy", {}).get("mood", "calm")
duration_minutes = idea.get("duration_minutes", 480)
duration_label = "10 Hours" if duration_minutes >= 600 else "8 Hours"

def strip_emojis(text):
    """Remove emojis — ffmpeg drawtext doesn't support them without emoji font."""
    import re
    emoji_pattern = re.compile(
        "["
        "😀-🙏"
        "🌀-🗿"
        "🚀-🛿"
        "🇠-🇿"
        "✀-➿"
        "🤀-🧿"
        "☀-⛿"
        "🨀-🩯"
        "🩰-🫿"
        "]+",
        flags=re.UNICODE
    )
    return emoji_pattern.sub("", text).strip()

is_flagship = idea.get("is_flagship") or idea.get("content_tier") == "flagship"
flagship_shorts = (idea.get("flagship_package", {}) or {}).get("shorts", [])
print(f"Generating Short for: {theme} ({primary}) | flagship={is_flagship}")

# ─────────────────────────────────────────────
# HOOK ROTATION — cycles POV → Educational → Contrast
# ─────────────────────────────────────────────
HOOK_STYLES = ["pov", "educational"]

if os.path.exists(SHORT_ROTATION_FILE):
    with open(SHORT_ROTATION_FILE) as f:
        rotation = json.load(f)
    last_style = rotation.get("last_style", "contrast")
    idx = HOOK_STYLES.index(last_style) if last_style in HOOK_STYLES else -1
    hook_style = HOOK_STYLES[(idx + 1) % len(HOOK_STYLES)]
else:
    hook_style = "pov"

with open(SHORT_ROTATION_FILE, "w") as f:
    json.dump({"last_style": hook_style}, f)

print(f"Hook style this Short: {hook_style}")

# ─────────────────────────────────────────────
# HOOK TEXT + VOICEOVER — generated by Claude
# ─────────────────────────────────────────────

SOFT_CTAS = [
    "Full version on Midnight Cabin.",
    "Save this for tonight.",
    "Let the full version play later.",
]

# Fallback hooks if LLM fails
POV_HOOKS_FALLBACK = {
    "rain":         "POV: your brain finally stopped",
    "fireplace":    "POV: you have nowhere to be tonight",
    "river":        "POV: the overthinking just stopped",
    "ocean_waves":  "POV: the ocean is breathing for you",
    "soft_wind":    "POV: nothing needs you right now",
    "night_forest": "POV: the whole world got quiet",
    "brown_noise":  "POV: you can finally think clearly",
}

EDUCATIONAL_HOOKS_FALLBACK = {
    "rain":         "Why your brain loves this sound",
    "fireplace":    "Why a fire feels like someone is home",
    "river":        "Why rivers quiet a loud brain",
    "ocean_waves":  "Why waves are your oldest sleep cue",
    "soft_wind":    "Why wind sounds feel like safety",
    "night_forest": "Why nature sounds lower your threat response",
    "brown_noise":  "Why this frequency quiets anxious brains",
}

FALLBACK_HOOKS = {
    "pov": POV_HOOKS_FALLBACK,
    "educational": EDUCATIONAL_HOOKS_FALLBACK,
}

POV_VOICEOVERS_FALLBACK = {
    "rain": f"You know that feeling when the rain starts and your whole body just... exhales? That's what this is. {duration_label} of it, no interruptions. Save this for tonight.",
    "fireplace": f"There's something about a fire that makes your brain think someone is home, you're safe, nothing is waiting. That's the whole point. Save this for 10pm.",
    "river": f"A river doesn't ask anything of you. It just keeps moving, and somewhere in that rhythm your brain finds something to follow that isn't your own thoughts. Save this for tonight.",
    "ocean_waves": f"The ocean has been doing this since before you were born. Arrive, fade, return. Your brain recognises it before you do. Save this for when you can't sleep.",
    "soft_wind": f"Wind is the sound of nothing needing you right now. Just a quiet room, and air moving the way it always has. Save this for tonight.",
    "night_forest": f"The forest is never completely silent. But nothing in it is demanding your attention either. Your nervous system knows the difference. Save this for tonight.",
    "brown_noise": f"Your brain is always scanning for threats. Brown noise gives it something consistent to latch onto so it stops. That's why it works. Save this for when your thoughts are too loud.",
}

EDUCATIONAL_VOICEOVERS_FALLBACK = {
    "rain": f"Your auditory cortex keeps scanning for changes even while you sleep. Steady rain masks those changes so your brain stops looking. That's why it works. Save this for tonight.",
    "fireplace": f"Irregular crackling keeps your auditory system just engaged enough to suppress intrusive thoughts — but not enough to keep you awake. Save this for 10pm.",
    "river": f"Pink noise in flowing water closely matches the brain's own resting neural rhythms. Your mind recognises it and slows to match. Save this for when you can't sleep.",
    "ocean_waves": f"Ocean waves arrive at roughly 12 cycles per minute — almost exactly the breathing rate of someone in deep sleep. Your body takes the cue. Save this for tonight.",
    "soft_wind": f"Pink noise in wind sounds is linked to better memory consolidation. Your brain doesn't just rest — it recovers. Save this for tonight.",
    "night_forest": f"Nature sounds reduce activity in the amygdala — the brain's threat detection centre. Your body stops bracing. That's what rest actually feels like. Save this for tonight.",
    "brown_noise": f"Brown noise shifts neural activity toward the prefrontal cortex — which is exactly the part that struggles most with focus and with rumination. Save this for when your brain won't stop.",
}

FALLBACK_VOICEOVERS = {
    "pov": POV_VOICEOVERS_FALLBACK,
    "educational": EDUCATIONAL_VOICEOVERS_FALLBACK,
}

def generate_short_content(primary, hook_style, duration_label, theme, mood):
    """Use Claude to generate fresh hook text and voiceover."""
    anthropic_key = os.environ.get("ANTHROPIC_API_KEY", "")
    if not anthropic_key:
        print("ANTHROPIC_API_KEY not set — using fallback content")
        return None, None

    try:
        import anthropic as _anthropic
        import re as _re

        client = _anthropic.Anthropic(api_key=anthropic_key)

        # Load recently used hooks to avoid repeats
        hooks_log_path = os.path.join(PERSISTENT_DIR, "used_hooks.json")
        used_hooks = []
        try:
            if os.path.exists(hooks_log_path):
                with open(hooks_log_path) as f:
                    used_hooks = json.load(f).get(primary, [])[-10:]
        except Exception:
            pass

        recent_hooks_str = (
            "\nAvoid these recently used hook texts (do NOT repeat them):\n" +
            "\n".join(f"- {h}" for h in used_hooks)
        ) if used_hooks else ""

        prompt = f"""You are writing content for a YouTube Shorts video for @midnightcabins — a sleep and focus ambient sound channel.

The channel's breakthrough insight: "Why your brain loves rain at night" gets 3-10x more views
than "Rain sounds for sleep." The difference is psychological — emotional recognition beats utility labels.

This Short's job: make someone stop scrolling, feel personally understood, and save it for later.

Theme: {theme}
Primary sound: {primary.replace("_", " ")}
Mood: {mood}
Full video duration: {duration_label}
Hook style: {hook_style}{recent_hooks_str}

Generate TWO things:

1. HOOK_TEXT — shown as large text on screen for 2 seconds while scrolling
   - Max 5 words, no punctuation except apostrophes
   - No emojis (they break video rendering)
   - Must create EMOTIONAL RECOGNITION — the viewer should think "that's me"
   - Style guide:
     * POV style: Start with "POV:" then a specific emotional state, NOT a scene description
       GOOD: "POV: your brain finally stopped" / "POV: nothing needs you right now"
       BAD: "POV: The cabin is quiet" / "POV: Rain is falling" (scenes, not feelings)
     * Educational style: A "why your brain" insight that makes people curious about themselves
       GOOD: "Why your brain loves this sound" / "Why this quiets anxious minds"
       BAD: "Rain masks every other sound" (too clinical, no personal pull)
   - Do NOT use: exclamation marks, hashtags, all caps, generic phrases

2. VOICEOVER — spoken aloud by a calm voice, max 35 words
   - Warm, specific, slightly poetic — like a thoughtful friend at midnight, not a wellness brand
   - Must end with: "Save this for tonight." (this is the save trigger — always use this exact phrase)
   - Do NOT mention: subscribe, like, comment, algorithm, YouTube, "Full version"
   - Do NOT start with "I"
   - POV style: Make the listener feel understood in their specific emotional state
   - Educational style: One genuine brain-science insight that makes the person think "oh, that's why"
   - The voiceover should feel like it was written specifically about the person listening

Return ONLY valid JSON, no markdown:
{{"hook_text": "...", "voiceover": "..."}}"""

        response = client.messages.create(
            model="claude-haiku-4-5-20251001",
            max_tokens=200,
            temperature=0.9,
            messages=[{"role": "user", "content": prompt}]
        )

        text = response.content[0].text.strip()
        text = _re.sub(r"```json|```", "", text).strip()
        data = json.loads(text)

        hook = data.get("hook_text", "").strip()
        vo = data.get("voiceover", "").strip()

        # Validate
        if not hook or len(hook) > 45:
            print(f"LLM hook too long ({len(hook)} chars): '{hook}' — using fallback")
            return None, None
        if not vo or len(vo.split()) > 40:
            print(f"LLM voiceover too long or empty — using fallback")
            return None, None

        print(f"LLM hook: {hook}")
        print(f"LLM voiceover: {vo[:60]}...")

        # Save hook to used log to prevent repeats in future runs
        try:
            hooks_log_path = os.path.join(PERSISTENT_DIR, "used_hooks.json")
            all_hooks = {}
            if os.path.exists(hooks_log_path):
                with open(hooks_log_path) as f:
                    all_hooks = json.load(f)
            niche_hooks = all_hooks.get(primary, [])
            if hook not in niche_hooks:
                niche_hooks.append(hook)
            all_hooks[primary] = niche_hooks[-20:]  # keep last 20 per niche
            with open(hooks_log_path, "w") as f:
                json.dump(all_hooks, f, indent=2)
        except Exception:
            pass

        return hook, vo

    except Exception as e:
        print(f"LLM generation failed: {e} — using fallback")
        return None, None

# Generate via LLM
hook_text, voiceover_text = generate_short_content(
    primary, hook_style, duration_label, theme, mood
)

# Fallback to pre-written content if LLM fails
if not hook_text:
    hook_text = FALLBACK_HOOKS[hook_style].get(primary, "Save this sound for tonight")

if not voiceover_text:
    voiceover_text = FALLBACK_VOICEOVERS[hook_style].get(
        primary,
        f"{theme}. {duration_label} of uninterrupted ambient sound. Full version on Midnight Cabin."
    )

cta_text = random.choice([
    "Save this for tonight",
    f"Full {duration_label} on Midnight Cabin",
    "Let this play later",
])

# Strip emojis for drawtext (ffmpeg default font doesn't support emoji)
hook_text_display = strip_emojis(hook_text)
cta_text_display = strip_emojis(cta_text)

# ─────────────────────────────────────────────
# THEME-SPECIFIC START OFFSETS
# Best-sounding moment per theme
# ─────────────────────────────────────────────
START_OFFSET_RANGES = {
    "rain":         (30,  180),
    "fireplace":    (20,  120),
    "river":        (45,  240),
    "ocean_waves":  (60,  300),
    "soft_wind":    (20,  150),
    "night_forest": (90,  300),
    "brown_noise":  (5,   120),
    "thunder":      (30,  180),
}
lo, hi = START_OFFSET_RANGES.get(primary, (30, 180))
START_OFFSET = random.randint(lo, hi)
print(f"Starting Short at offset: {START_OFFSET}s")

# ─────────────────────────────────────────────
# GENERATE VOICEOVER via Google Cloud TTS
# ─────────────────────────────────────────────
def generate_voiceover(text, output_path):
    import urllib.request
    import urllib.error
    import base64
    import ssl

    # Fix macOS SSL cert verification
    ssl_context = ssl.create_default_context()
    try:
        import certifi
        ssl_context = ssl.create_default_context(cafile=certifi.where())
    except ImportError:
        ssl_context.check_hostname = False
        ssl_context.verify_mode = ssl.CERT_NONE

    api_key = os.environ.get("GOOGLE_TTS_API_KEY", "")

    if not api_key:
        print("GOOGLE_TTS_API_KEY not set — skipping voiceover")
        subprocess.run([
            "ffmpeg", "-y",
            "-f", "lavfi", "-i", "anullsrc=r=44100:cl=mono",
            "-t", "3", "-q:a", "9", "-acodec", "libmp3lame",
            output_path
        ], capture_output=True)
        return False

    payload = json.dumps({
        "input": {"text": text},
        "voice": {
            "languageCode": "en-US",
            "name": "en-US-Neural2-F",  # warm, natural female voice
            "ssmlGender": "FEMALE"
        },
        "audioConfig": {
            "audioEncoding": "MP3",
            "speakingRate": 0.95,
            "pitch": -1.0,
        }
    }).encode("utf-8")

    url = f"https://texttospeech.googleapis.com/v1/text:synthesize?key={api_key}"
    req = urllib.request.Request(
        url, data=payload,
        headers={"Content-Type": "application/json"}
    )

    try:
        with urllib.request.urlopen(req, timeout=30, context=ssl_context) as resp:
            result = json.loads(resp.read())
            audio_data = base64.b64decode(result["audioContent"])
            with open(output_path, "wb") as f:
                f.write(audio_data)
            print(f"Voiceover generated: {len(audio_data)} bytes")
            return True
    except Exception as e:
        print(f"TTS failed: {e}")
        subprocess.run([
            "ffmpeg", "-y",
            "-f", "lavfi", "-i", "anullsrc=r=44100:cl=mono",
            "-t", "3", "-q:a", "9", "-acodec", "libmp3lame",
            output_path
        ], capture_output=True)
        return False

has_voiceover = generate_voiceover(voiceover_text, VOICEOVER_PATH)

def get_duration(path):
    result = subprocess.run(
        ["ffprobe", "-v", "error", "-show_entries", "format=duration",
         "-of", "default=noprint_wrappers=1:nokey=1", path],
        capture_output=True, text=True
    )
    try:
        return float(result.stdout.strip())
    except Exception:
        return 3.0

vo_duration = get_duration(VOICEOVER_PATH) if os.path.exists(VOICEOVER_PATH) else 3.0
print(f"Voiceover duration: {vo_duration:.1f}s")

# ─────────────────────────────────────────────
# BUILD FILTER GRAPH
# ─────────────────────────────────────────────
def escape_text(text):
    return (text
        .replace("\\", "\\\\")
        .replace("'", "\\'")
        .replace(":", "\\:")
        .replace("%", "\\%")
        .replace("\n", "\\n"))

# No wrapping — use single line with smaller font to avoid join typos
# LLM is instructed to keep hook under 6 words so it fits
hook_wrapped = escape_text(hook_text_display)
cta_escaped = escape_text(cta_text_display)
channel_escaped = escape_text("@midnightcabins")

hook_show_until = min(vo_duration + 2, 9)

# For contrast style — show silence label first 5s, then sound label
# ─────────────────────────────────────────────
# FONT SELECTION
# Uses best available font on current platform
# Falls back gracefully if font not found
# ─────────────────────────────────────────────

def find_font():
    """Find best available TTF font for the current platform."""
    system = platform.system()

    if system == "Darwin":  # macOS — use TTF only, avoid TTC
        mac_fonts = [
            "/System/Library/Fonts/Supplemental/Georgia.ttf",
            "/Library/Fonts/Arial.ttf",
            "/System/Library/Fonts/Supplemental/Verdana.ttf",
            "/System/Library/Fonts/Supplemental/Trebuchet MS.ttf",
        ]
        for path in mac_fonts:
            if os.path.exists(path):
                return path
        # Search user fonts
        user_fonts = os.path.expanduser("~/Library/Fonts")
        for f in ["Arial.ttf", "Helvetica.ttf", "Georgia.ttf"]:
            p = os.path.join(user_fonts, f)
            if os.path.exists(p):
                return p

    else:  # Linux / Railway (Debian trixie)
        linux_fonts = [
            "/usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf",
            "/usr/share/fonts/truetype/liberation2/LiberationSans-Regular.ttf",
            "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
            "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf",
            "/usr/share/fonts/opentype/noto/NotoSansCJK-Regular.ttc",
        ]
        for path in linux_fonts:
            if os.path.exists(path):
                return path

    return ""  # ffmpeg default font

FONT_FILE = find_font()
# Escape font path for ffmpeg filter string
font_path_escaped = FONT_FILE.replace("\\", "/").replace(":", "\\:").replace("'", "\\'") if FONT_FILE else ""
font_attr = f":fontfile='{font_path_escaped}'" if font_path_escaped else ""
print(f"Using font: {FONT_FILE or 'ffmpeg default'}")

# Niche audio EQ — each sound gets subtle frequency shaping
NICHE_AUDIO_EQ = {
    "rain":         "equalizer=f=200:width_type=o:width=2:g=1,equalizer=f=8000:width_type=o:width=2:g=-3",
    "fireplace":    "equalizer=f=100:width_type=o:width=2:g=3,equalizer=f=6000:width_type=o:width=2:g=-4",
    "river":        "equalizer=f=500:width_type=o:width=2:g=2,equalizer=f=8000:width_type=o:width=2:g=-2",
    "ocean_waves":  "equalizer=f=150:width_type=o:width=2:g=2,equalizer=f=7000:width_type=o:width=2:g=-3",
    "soft_wind":    "equalizer=f=300:width_type=o:width=2:g=1,equalizer=f=9000:width_type=o:width=2:g=-2",
    "night_forest": "equalizer=f=400:width_type=o:width=2:g=2,equalizer=f=8000:width_type=o:width=2:g=-2",
    "brown_noise":  "equalizer=f=100:width_type=o:width=2:g=2,equalizer=f=5000:width_type=o:width=2:g=-1",
    "thunder":      "equalizer=f=80:width_type=o:width=2:g=4,equalizer=f=8000:width_type=o:width=2:g=-5",
}
niche_eq = NICHE_AUDIO_EQ.get(primary, "")
ambient_fade = f"afade=t=in:st=0:d=2,{niche_eq}" if niche_eq else "afade=t=in:st=0:d=2"

# Niche colour grades — each sound type gets a distinct visual feel
NICHE_COLOR_GRADE = {
    "rain":         "eq=contrast=1.05:saturation=0.75:brightness=-0.04,colorbalance=bs=0.04",
    "fireplace":    "eq=contrast=1.08:saturation=1.15:brightness=0.02,colorbalance=rs=0.06",
    "river":        "eq=contrast=1.04:saturation=0.85:brightness=-0.02,colorbalance=gs=0.03",
    "ocean_waves":  "eq=contrast=1.06:saturation=0.80:brightness=-0.03,colorbalance=bs=0.05",
    "soft_wind":    "eq=contrast=1.03:saturation=0.90:brightness=0.01",
    "night_forest": "eq=contrast=1.07:saturation=0.70:brightness=-0.05,colorbalance=gs=0.04",
    "brown_noise":  "eq=contrast=1.04:saturation=0.65:brightness=-0.03",
    "thunder":      "eq=contrast=1.10:saturation=0.60:brightness=-0.06,colorbalance=bs=0.03",
}
color_grade = NICHE_COLOR_GRADE.get(primary, "eq=contrast=1.04:saturation=0.85")

# Build vf — fontsize 44 fits 6-word hook on one line without wrapping
vf = (
    f"scale=1080:1920:force_original_aspect_ratio=increase,"
    f"crop=1080:1920,"
    f"{color_grade},"
    f"drawtext=text='{hook_wrapped}'{font_attr}"
    f":fontsize=38:fontcolor=white"
    f":x=(w-text_w)/2:y=h/4"
    f":box=1:boxcolor=black@0.35:boxborderw=24"
    f","
    f"drawtext=text='{cta_escaped}'{font_attr}"
    f":fontsize=34:fontcolor=white"
    f":x=(w-text_w)/2:y=3*h/4"
    f":box=1:boxcolor=black@0.4:boxborderw=16"
    f","
    f"drawtext=text='{channel_escaped}'{font_attr}"
    f":fontsize=26:fontcolor=white@0.55"
    f":x=(w-text_w)/2:y=h-65,"
    f"format=yuv420p"
)

# ─────────────────────────────────────────────
# PICK VIDEO SOURCE — niche-aware
# ─────────────────────────────────────────────
LIBRARY_DIR = os.path.join(BASE_DIR, "video", "library")

def pick_library_image_for_niche(niche):
    folder = os.path.join(LIBRARY_DIR, niche)
    if not os.path.exists(folder):
        folder = LIBRARY_DIR
    if not os.path.exists(folder):
        return None
    images = [os.path.join(folder, f) for f in os.listdir(folder)
              if f.lower().endswith((".jpg", ".jpeg", ".png"))]
    return random.choice(images) if images else None

VISUAL_META_PATH = os.path.join(PERSISTENT_DIR, "current_visual.json")
animated_niche = None
try:
    if os.path.exists(VISUAL_META_PATH):
        with open(VISUAL_META_PATH) as _vmf: _vm = json.load(_vmf)
        animated_niche = _vm.get("primary") or _vm.get("primary_category")
except Exception:
    pass

# Check all possible locations for animated video
BG_ANIMATED_PERSISTENT = os.path.join(PERSISTENT_DIR, "bg_animated.mp4")

print(f"DEBUG — checking video sources:")
print(f"  bg_animated (app):        {BG_ANIMATED} — exists={os.path.exists(BG_ANIMATED)}")
print(f"  bg_animated (persistent): {BG_ANIMATED_PERSISTENT} — exists={os.path.exists(BG_ANIMATED_PERSISTENT)}")
print(f"  source video:             {SOURCE_VIDEO} — exists={os.path.exists(SOURCE_VIDEO)}")
print(f"  bg.jpg:                   {BG_IMAGE} — exists={os.path.exists(BG_IMAGE)}")

animated_matches_niche = (animated_niche is None or animated_niche == primary)

if os.path.exists(BG_ANIMATED) and animated_matches_niche:
    print(f"✅ Using animated bg — niche matches: {primary}")
    SHORT_VIDEO_SOURCE = BG_ANIMATED
    USE_LOOP = True
elif os.path.exists(BG_ANIMATED_PERSISTENT) and animated_matches_niche:
    print(f"✅ Using animated bg (persistent) — niche: {primary}")
    SHORT_VIDEO_SOURCE = BG_ANIMATED_PERSISTENT
    import shutil as _shutil2
    _shutil2.copy(BG_ANIMATED_PERSISTENT, BG_ANIMATED)
    USE_LOOP = True
else:
    if not animated_matches_niche:
        print(f"⚠️  Animated bg niche '{animated_niche}' != '{primary}' — using library image")
    library_image = pick_library_image_for_niche(primary)
    if library_image:
        print(f"✅ Using library image for '{primary}': {library_image}")
        STATIC_BG = os.path.join(BASE_DIR, "output", "short_bg_static.mp4")
        static_result = subprocess.run([
            "ffmpeg", "-y", "-loop", "1", "-i", library_image,
            "-t", str(SHORT_DURATION + 5),
            "-vf", f"scale=1080:1920:force_original_aspect_ratio=increase,crop=1080:1920,{color_grade},format=yuv420p",
            "-c:v", "libx264", "-preset", "ultrafast", "-crf", "28", "-r", "30", STATIC_BG
        ], capture_output=True, text=True)
        SHORT_VIDEO_SOURCE = STATIC_BG if static_result.returncode == 0 else (SOURCE_VIDEO if os.path.exists(SOURCE_VIDEO) else None)
        USE_LOOP = True if static_result.returncode == 0 else False
    elif os.path.exists(SOURCE_VIDEO):
        SHORT_VIDEO_SOURCE = SOURCE_VIDEO
        USE_LOOP = False
    else:
        raise FileNotFoundError("No video source found for Short")

if USE_LOOP:
    # Loop the 5s animated clip, take audio from main video
    if has_voiceover and os.path.exists(VOICEOVER_PATH):
        filter_complex = (
            f"[1:a]{ambient_fade},volume=0.5[ambient];"
            f"[2:a]volume=1.1,adelay=300|300[vo];"
            f"[ambient][vo]amix=inputs=2:duration=first:weights=1 1[audio]"
        )
        cmd = [
            "ffmpeg", "-y",
            "-stream_loop", "-1", "-i", SHORT_VIDEO_SOURCE,
            "-ss", str(START_OFFSET), "-t", str(SHORT_DURATION), "-i", SOURCE_VIDEO,
            "-i", VOICEOVER_PATH,
            "-t", str(SHORT_DURATION),
            "-filter_complex", filter_complex,
            "-vf", vf,
            "-map", "0:v",
            "-map", "[audio]",
            "-c:v", "libx264", "-preset", "fast", "-crf", "22",
            "-c:a", "aac", "-b:a", "192k",
            "-r", "30", "-movflags", "+faststart",
            SHORT_OUTPUT
        ]
    else:
        cmd = [
            "ffmpeg", "-y",
            "-stream_loop", "-1", "-i", SHORT_VIDEO_SOURCE,
            "-ss", str(START_OFFSET), "-t", str(SHORT_DURATION), "-i", SOURCE_VIDEO,
            "-t", str(SHORT_DURATION),
            "-vf", vf,
            "-map", "0:v",
            "-map", "1:a",
            "-af", f"{ambient_fade},volume=0.5",
            "-c:v", "libx264", "-preset", "fast", "-crf", "22",
            "-c:a", "aac", "-b:a", "192k",
            "-r", "30", "-movflags", "+faststart",
            SHORT_OUTPUT
        ]
elif has_voiceover and os.path.exists(VOICEOVER_PATH):
    filter_complex = (
        f"[0:a]{ambient_fade},volume=0.5[ambient];"
        f"[1:a]volume=1.1,adelay=300|300[vo];"
        f"[ambient][vo]amix=inputs=2:duration=first:weights=1 1[audio]"
    )
    cmd = [
        "ffmpeg", "-y",
        "-ss", str(START_OFFSET), "-t", str(SHORT_DURATION),
        "-i", SHORT_VIDEO_SOURCE,
        "-i", VOICEOVER_PATH,
        "-filter_complex", filter_complex,
        "-vf", vf,
        "-map", "0:v", "-map", "[audio]",
        "-c:v", "libx264", "-preset", "fast", "-crf", "22",
        "-c:a", "aac", "-b:a", "192k",
        "-r", "30", "-movflags", "+faststart",
        SHORT_OUTPUT
    ]
else:
    cmd = [
        "ffmpeg", "-y",
        "-ss", str(START_OFFSET), "-t", str(SHORT_DURATION),
        "-i", SHORT_VIDEO_SOURCE,
        "-vf", vf,
        "-af", f"{ambient_fade},volume=0.5",
        "-c:v", "libx264", "-preset", "fast", "-crf", "22",
        "-c:a", "aac", "-b:a", "192k",
        "-r", "30", "-movflags", "+faststart",
        SHORT_OUTPUT
    ]

print(f"Rendering Short ({hook_style} style)...")
result = subprocess.run(cmd, capture_output=True, text=True)

if result.returncode != 0:
    print("Short render failed:", result.stderr[-800:])
    raise RuntimeError("Short render failed")

print(f"Short rendered successfully: {SHORT_OUTPUT}")

# ─────────────────────────────────────────────
# SAVE METADATA
# ─────────────────────────────────────────────
short_meta = {
    "theme": theme,
    "primary": primary,
    "layers": layers,
    "mood": mood,
    "duration_label": duration_label,
    "hook_style": hook_style,
    "hook_text": hook_text,
    "is_flagship": bool(is_flagship),
    "flagship_short_plan": flagship_shorts,
    "voiceover_text": voiceover_text,
    "has_voiceover": has_voiceover,
    "start_offset": START_OFFSET,
    "created_at": datetime.now().isoformat(),
}

with open(os.path.join(PERSISTENT_DIR, "current_short.json"), "w") as f:
    json.dump(short_meta, f, indent=2)

print(f"Short metadata saved — style: {hook_style}, offset: {START_OFFSET}s")